Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
app/views/static_pages/index.html.erb
config/environments/development.rb
config/environments/production.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20160724023544_devise_create_users.rb
db/schema.rb
test/fixtures/users.yml
test/models/user_test.rb

Integrating Bootstrap and Devise

Integrate the common things

---

Gemfile
Gemfile.lock
app/assets/javascripts/games.js.coffee
app/assets/stylesheets/games.scss
app/controllers/games_controller.rb
app/controllers/static_pages_controller.rb
app/helpers/games_helper.rb
app/models/game.rb
app/views/games/new.html.erb
app/views/games/show.html.erb
app/views/static_pages/index.html.erb
config/initializers/simple_form.rb
config/locales/simple_form.en.yml
config/routes.rb
db/migrate/20160724212652_create_games.rb
db/schema.rb
lib/templates/erb/scaffold/_form.html.erb
test/controllers/games_controller_test.rb
test/fixtures/games.yml
test/helpers/games_helper_test.rb
test/models/game_test.rb

- Installed simple_form gem
- Generated games controller
- Generated model game with name field
- Added placeholder controller actions for new, create, and show
- Added basic simple_form for creating a new game (view)
- Added routes for new, create, and show

Added simpleform, games model

---

app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/unlocks/new.html.erb

- Regenerate devise views to use simple forms

Devise integration part 2

---

app/models/game.rb
app/models/piece.rb
app/models/user.rb
config/routes.rb
db/migrate/20160728022917_add_ids_to_game.rb
db/migrate/20160728023902_create_pieces.rb
db/migrate/20160728193153_add_index_to_pieces.rb
db/migrate/20160730005230_add_index_to_player_ids_in_games_table.rb
db/schema.rb
test/fixtures/pieces.yml
test/models/piece_test.rb

added piece model, edited games model to include player ids
hooked up pieces to games, and games to user
add piece resource under games

Set up models, and migrations

---

app/models/game.rb
spec/models/game_spec.rb

- add tests to check for correct position of pieces and number of pieces
- define method to populate board.
- runs well with rubocop

Populate Game

---

app/assets/stylesheets/master.css.scss
app/views/games/index.html.erb
app/views/games/show.html.erb

-Added chess board on games#show page
-Added master.css.scss file to app/assets/stylesheets to style chess board

Built view for chess board

---

app/assets/stylesheets/master.css.scss
app/controllers/games_controller.rb
app/models/game.rb
app/views/games/show.html.erb

Draw Pieces on board
- create render_pieces method in games.rb
- refactor show.html.erb to use loops to display individual game tile

Draw pieces on board

---

app/models/piece.rb
spec/models/piece_spec.rb

Pull request for the capture logic (move_to! method). Placeholder pull request (work in progress).

Capture Logic: move_to! method

---

app/assets/javascripts/pieces.js.coffee
app/assets/stylesheets/master.css.scss
app/assets/stylesheets/pieces.scss
app/controllers/pieces_controller.rb
app/helpers/games_helper.rb
app/helpers/pieces_helper.rb
app/models/game.rb
app/views/games/show.html.erb
app/views/pieces/show.html.erb
config/routes.rb
spec/controllers/games_controller_spec.rb
spec/controllers/pieces_controller_spec.rb
spec/factories.rb
spec/helpers/pieces_helper_spec.rb
spec/models/game_spec.rb

Set up board to move pieces around.
- Set up pieces/show.html.erb
- wrap links around pieces in games/show.html.erb
- Tests written for show and update action for pieces controller
- show and update action methods done

Support moving pieces

---

app/models/pieces/knight.rb
spec/factories.rb
spec/models/pieces/knight_spec.rb

- Set up tests in rspec to check if moves are valid
- Set up valid_move method

Set up knight to check if moves are valid

---

app/models/pieces/pawn.rb
spec/factories.rb
spec/models/pieces/pawn_spec.rb

valid_move? method for pawn

---

Gemfile.lock
app/models/pieces/rook.rb
spec/factories.rb
spec/models/pieces/rook_spec.rb

Created valid_move? method for rook
Created a rook factory
Created tests for valid_move? in rook_spec
Get it running green with rubocop

Rook valid move

---

app/models/pieces/queen.rb
spec/factories.rb
spec/models/pieces/queen_spec.rb

Create queen valid_move? method
Create factory for queen and implement tests
Bribe rubocop  :+1:

Queen valid move

---

Gemfile.lock
app/models/pieces/queen.rb
spec/factories.rb
spec/models/pieces/queen_spec.rb

Queen obstructed? in valid_move?

---

app/models/pieces/bishop.rb
spec/factories.rb
spec/models/pieces/bishop_spec.rb

- Added valid_move? method for bishop piece
- Created bishop piece factory
- Created tests for bishop piece

Valid move method and tests for bishop piece

---

config/initializers/devise.rb

Add callback parameter to devise.rb for omniauth integration

Add callback URL to config/initializers/devise.rb for FB integration

---

app/models/pieces/king.rb

- Fixed the valid move method for the king piece

Fixed valid move for king piece

---

app/controllers/games_controller.rb
app/models/game.rb
app/views/games/show.html.erb
app/views/pieces/show.html.erb
config/routes.rb
db/migrate/20160814231018_add_forefeit_or_active_status.rb
db/schema.rb
spec/models/game_spec.rb

- Added forfeit, active, and winner_id fields to games table (also added indexes for each)
- Created forfeit! method in game model
- Created forfeit action in games controller
- Added forfeit route to routes
- Added forfeit method tests to games spec 
- Added forfeit button to allow users to forfeit from game
- Showed on game#show page whether game was active or inactive 
- Added CSS to style active vs. inactive game status

Added ability for users to forfeit game

---

app/controllers/pieces_controller.rb

Call move_to! to move pieces once valid_move checking has been completed

Call move_to! when moving pieces

---

app/assets/javascripts/games.js
app/assets/stylesheets/master.css.scss
app/views/games/show.html.erb

- Changed check so that it shows up on the page instead of alert box
- If a king is in check, status will appear as alert box at top of page
- If a king is no longer in check, status should disappear 
- I also moved the black player gravatar to the top of the board and the white player gravatar to the bottom of the board

Improved display of check

---

app/assets/javascripts/games.js
app/assets/stylesheets/master.css.scss
app/controllers/pieces_controller.rb
app/views/games/show.html.erb

- Modified pieces controller to incorporate stalemate
- Modified show page and javascript file so that alert flashes when stalemate occurs
- Added css to style alert

Stalemate status now displayed

---

README.rdoc

Added Travis badge to README

---

app/assets/javascripts/games.js
app/assets/stylesheets/master.css.scss
app/controllers/pieces_controller.rb
app/models/piece.rb
app/views/games/show.html.erb
app/views/static_pages/index.html.erb

Modified show.html.erb for game board display so row numbers start counting at 7 at top of board instead of 0 at top (to allow white pieces to be displayed at bottom of board)

Reverse row numbers in rendering of pieces

---

app/models/pieces/pawn.rb
spec/models/piece_spec.rb
spec/models/pieces/pawn_spec.rb

Bug fix: Fix bug which allows pawns to be moved diagonally without capture

Include checks for pawn valid move and rspec tests

---

app/assets/javascripts/games.js
app/assets/stylesheets/master.css.scss
app/controllers/pieces_controller.rb
app/models/game.rb
app/models/piece.rb
app/models/pieces/pawn.rb
app/views/games/show.html.erb
app/views/layouts/application.html.erb
spec/models/game_spec.rb

Check for checkmate in pieces_controller and pass result to javascript front-end

Checkmate front-end

---

app/models/game.rb
app/services/game/board_populator.rb
config/application.rb
spec/controllers/pieces_controller_spec.rb
spec/models/game_spec.rb
spec/models/pieces/queen_spec.rb
spec/models/pieces/rook_spec.rb
spec/services/game/board_populator_spec.rb

- Move populate board method into service object
- Created rspec spec file for board populator object
- Edit existing spec files to use service object instead of populate_board! method

Move populate board into service object

---

app/controllers/pieces_controller.rb
app/models/piece.rb
spec/models/piece_spec.rb
spec/models/pieces/pawn_spec.rb

Ensure that once a player is in check the player's move is a valid response to the check condition
Preliminary code **** work in progress ****

Verify check response
